### ISSUE TITLE
Pluma --plugins flag behaves unexpectedly

### ISSUE THREAD

**Issue by mjftw** [Witekio/pluma-automation#75]
**Describe the bug**
The Pluma `--plugin` flag is not working as intended, and gives some rubbish error messages.

The plugins directory specified should have the following structure:
`<plugindir>/module_name/<filename>.py`
and `<filename>.py` should contain the tests.

The error given when the plugins directory has the following structure is awful:
`<plugindir>/<filename>.py`
and `<filename>.py` should contain the tests.

(Probably this structure should be allowed anyway)
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c ./pluma.yml -t ./pluma-target.yml --plugin ./plugindir/ --debug check
No console defined in the device configuration file
Components:
    Serial:  None
    SSH:  None
    Prompt:  \S+@\S+:
    Login:  mendel
    Password:  ******
    Power control:  None
    Storage:  None
    USB Hub:  None

Traceback (most recent call last):
  File "/home/merlin/projects/pluma-automation/pluma/__main__.py", line 87, in main
    check_only=True)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 26, in execute_run
    target_config_path, show_tests_list=check_only)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 79, in build_test_controller
    testsConfig = TestsConfig(tests_config, Pluma.tests_providers())
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 34, in __init__
    self.__populate_tests(config)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 85, in __populate_tests
    self.tests = self.tests_from_sequence(sequence, self.test_providers)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 140, in tests_from_sequence
    supported_actions=supported_actions)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 156, in tests_from_action
    tests = provider.all_tests(key=action_key, config=Configuration(action_config))
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 31, in all_tests
    all_tests = self.find_python_tests()
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 64, in find_python_tests
    name=f'{cls.__module__[cls.__module__.index(module_name):]}.{class_name}',
ValueError: substring not found
substring not found
```

If the plugin dir structure does look correct, we get a different error in the `pluma.yaml`.

Plugin dir structure: `plugindir/testmodule/filesystem.py`

pluma.yml
```yaml
settings:
  continue_on_fail: true
  iterations: 1

sequence:
- core_tests:
    include: [testmodule.filesystem]
    exclude: []
    parameters:
      testmodule.filesystem.FileExists:
        path: '/bin/bash'
        run_on_host: true

```

```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma -c ./pluma.yml -t ./pluma-target.yml --plugin ./plugindir/ --debug check
No console defined in the device configuration file
Components:
    Serial:  None
    SSH:  None
    Prompt:  \S+@\S+:
    Login:  mendel
    Password:  ******
    Power control:  None
    Storage:  None
    USB Hub:  None

Traceback (most recent call last):
  File "/home/merlin/projects/pluma-automation/pluma/__main__.py", line 87, in main
    check_only=True)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 26, in execute_run
    target_config_path, show_tests_list=check_only)
  File "/home/merlin/projects/pluma-automation/pluma/cli/api.py", line 79, in build_test_controller
    testsConfig = TestsConfig(tests_config, Pluma.tests_providers())
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 34, in __init__
    self.__populate_tests(config)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 85, in __populate_tests
    self.tests = self.tests_from_sequence(sequence, self.test_providers)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 140, in tests_from_sequence
    supported_actions=supported_actions)
  File "/home/merlin/projects/pluma-automation/pluma/cli/testsconfig.py", line 156, in tests_from_action
    tests = provider.all_tests(key=action_key, config=Configuration(action_config))
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 34, in all_tests
    includes+excludes)
  File "/home/merlin/projects/pluma-automation/pluma/cli/pythontestsprovider.py", line 100, in validate_match_strings
    raise ValueError(f'Some include/exclude rules matched no tests: {not_matched}')
ValueError: Some include/exclude rules matched no tests: ['testmodule.filesystem']
Some include/exclude rules matched no tests: ['testmodule.filesystem']
(venv) merlin@pangolin:~/projects/pluma-automation$
```

Looks like the plugin dir is not being found?

**Comment by Pixep** [comment]
@mjftw I don't see how the PR you linked solves this issue? And was it really a bug, or just a missing `__init__.py`?
